version: "3.3"

services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_DB: 'iliad'
      POSTGRES_USER: 'developer'
      POSTGRES_PASSWORD: 'testing'
    networks:
      - defnet
networks:
    defnet:
      external: true